# Generated by Django 3.1.2 on 2020-11-01 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('userid',)},
        ),
    ]
