# Generated by Django 3.1.2 on 2020-11-05 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_review'),
        ('account', '0002_auto_20201101_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(max_length=50)),
                ('notification', models.CharField(max_length=12)),
                ('time_created', models.TimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('deliver_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
