# Generated by Django 3.1.2 on 2020-11-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_purchaseinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinfo',
            name='notification',
            field=models.CharField(max_length=120),
        ),
    ]
