# Generated by Django 3.1.2 on 2020-11-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20201105_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payout',
            field=models.IntegerField(default=0),
        ),
    ]
