# Generated by Django 3.1.2 on 2020-11-05 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_requestpayout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestpayout',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user'),
        ),
    ]
