# Generated by Django 3.1.2 on 2020-10-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20201027_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='media'),
        ),
    ]
