# Generated by Django 3.1.2 on 2020-10-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20201028_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='./'),
        ),
    ]
