# Generated by Django 3.1.2 on 2020-11-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20201103_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='./'),
        ),
    ]
