# Generated by Django 3.1.2 on 2020-11-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='global_delivery',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='india_delivery',
            field=models.IntegerField(default=100),
        ),
    ]
