# Generated by Django 3.1.2 on 2020-10-30 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20201028_1922'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('product', 'userid')},
        ),
    ]
